name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install Client Dependencies
        run: |
          cd react-postgres
          npm install
      - name: Install Server Dependencies
        run: |
          cd server
          npm install
      # - name: Setup DB
      #   run: |
      #     ./server/db/init.sh
      #     ./server/migrate.sh
